version: "3.8"
services:
  # Django Web Application Service
  web:
    build: .
    command: ["python","manage.py","runserver","0.0.0.0:8000"]
    volumes:
      - .:/app
      - static_data:/app/staticfiles
    user: appuser
    ports:
      - "8000:8000"
    # We use env_file to load the bulk of our settings like SECRET_KEY, DEBUG, etc.
    env_file:
      - .env
    environment:
      - SITE_DOMAIN=localhost:8000
      - SITE_NAME=SCRAPPER_Project
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - db
      - redis
    restart: on-failure
    networks:
      - app_network

  # Celery Worker Service
  celery_worker:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: ${REDIS_URL}
      CELERY_RESULT_BACKEND: ${REDIS_URL}
    user: "appuser:appgroup"
    depends_on:
      - web
      - redis
    restart: on-failure
    networks:
      - app_network

  # Redis Service
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  # Flower Service
  flower:
    image: mher/flower
    command: celery -A core flower --broker=${CELERY_BROKER_URL} --port=5555
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker

  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app_network

# Define named volumes for persistent data storage.
volumes:
  pg_data:
  redis_data:
  static_data:

# Define a custom bridge network for internal communication.
networks:
  app_network:
    driver: bridge
